### PR TITLE
bring ingame mod options back

### PR DESCRIPTION
**Pull request by BangL**

### CODE REVIEW

**Comment by BangL** [comment]
this fixes
https://github.com/JamesWilko/Payday-2-BLT/issues/91
https://github.com/JamesWilko/Payday-2-BLT/issues/120
and
https://github.com/JamesWilko/Payday-2-BLT/issues/118

**Comment by BangL** [comment]
and #27

**Comment by neico** [comment]
I already did this manually as it was bugging me the hell out of it.  
especially if you have to adjust some hud offsets which you can only see ingame.

Not to mention that the custom menu hooks are still being called for the pause menu and therefore cause "parent menu missing" warnings

**Comment by BangL** [comment]
obsolete due to
https://github.com/JamesWilko/Payday-2-BLT-Lua/commit/89240f957c22303141a50efc91d8b4b8fbc9a96c

**Pull request closed without merging**
