### PR TITLE
Correcting mod manager color behavior

### PR DESCRIPTION
**Pull request by WNivek**
[0, 255] RGB color values from mod.txt now properly translated to expected [0, 1] ARGB.

### CODE REVIEW

**Comment by TdlQ** [comment]
And those who set their mod's color on the 0-1 range are screwed...

**Comment by WNivek** [comment]
The documentation clearly illustrates usage of a 0-255 range.  This change merely brings functionality in line with the documentation.

**Comment by TdlQ** [comment]
Oh... The documentation is bugged? Then fix the documentation! (Yes, I'm not pleased at all to be forced to update my 26 colored mods. My documentation is written in Lua and is always correct.)

**Comment by WNivek** [comment]
I will also note that, according to the scripts package I had pulled down a while back, Overkill's own color definitions are also defined in terms 0-255 before being divided down to 0-1.  So altering the code to match the docs brings us closer to the approach of the original devs.

**Comment by Luffyyy** [comment]
In my opinion it should stay 0-1 since it's how overkill uses it.
and yes do a search on all of the scripts of the game you'll see that 0-1 is much more used.

**Comment by TdlQ** [comment]
Actually, why not supporting both ways?

    self.color = Color(unpack(self.color))
    if self.color[1] > 1 or self.color[2] > 1 or self.color[3] > 1 then
        self.color = self.color / 255
    end

**Comment by Luffyyy** [comment]
Guess that's it  ¯\_(ツ)_/¯

**Comment by JamesWilko** [comment]
Supporting both 0-1 and 0-255 is trivial (8e9ddf4), documentation states 0-255 because thats easier to get values since you can just pull them from Photoshop or whatever.

**Pull request closed without merging**
